config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', :as => :logout

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :name, presence: true, length: { maximum: 60 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(user_path(@user.id), notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:show, :new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :public_email, :location, :organization, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :require_login, only: :index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasierMap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="nav">
    <% if current_user %>
    <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
    <%= link_to "Logout", :logout, method: :post %>
    <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
<div class="field">
  <%= label_tag :email %><br />
  <%= text_field_tag :email %>
</div>
<div class="field">
  <%= label_tag :password %><br />
  <%= password_field_tag :password %>
</div>
<div class="actions">
  <%= submit_tag "Login" %>
</div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>


<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :public_email %><br>
    <%= f.text_field :public_email, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form' %>
<%= link_to 'Back', user_path %>

app/views/users/new.html.erb
<h1>Sign In</h1>

<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= link_to 'Edit', edit_user_path %>
|
<%= link_to 'Delete', user_path, method: :delete, data: { confirm: 'Are you sure?' } %>

<div>
</div>

app/views/welcome/index.html.erb
<div class="nav">
<%= link_to "Sign in", new_user_path %>
</div>
<h3>Welcome!</h3>